version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=file:./dev.db
      - NEXTAUTH_SECRET=meridianbank-dev-secret-change-in-production
      - NEXTAUTH_URL=http://localhost:3000
    restart: unless-stopped
    volumes:
      - ./prisma/dev.db:/app/prisma/dev.db
